### ISSUE TITLE
"Set" innappropriate for adding TODO list

### ISSUE THREAD

**Issue by jhusain** [rolaveric/angular-falcor#1]
You should probably use call. That will require you to create a router though (no offline call). You can start with the router in the Falcor router demo. http://github.com/netflix/falcor-router-demo

**Comment by rolaveric** [comment]
Thanks @jhusain - I've implemented an express server + falcor router based off [falcor-router-demo](https://github.com/Netflix/falcor-router-demo) and [falcor-express-demo](https://github.com/Netflix/falcor-express-demo), and changed the client code to use `model.call()` instead of `model.set()` for adding items.

Thanks again for the tip, and thanks to you and the team for everything you've done with FalcorJS.
